services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  processor:
    build: .
    container_name: processor
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
      - STATION_ID=station-1
    depends_on:
      - rabbitmq
    volumes:
      - ./outputs:/app/outputs
      - ./rem:/app/rem
      - ./wait-for-rabbitmq.sh:/app/wait-for-rabbitmq.sh
    entrypoint: ["/app/wait-for-rabbitmq.sh", "python", "processor/realtime_pipeline.py"]
    restart: always
    healthcheck:
      test: ["CMD", "python", "processor/healthcheck.py"]
      interval: 15s
      timeout: 5s
      retries: 3


  ingest:
    build: .
    container_name: ingest
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASS=guest
    depends_on:
      - rabbitmq
    volumes:
      - ./wait-for-rabbitmq.sh:/app/wait-for-rabbitmq.sh
    entrypoint: ["/app/wait-for-rabbitmq.sh", "python", "ingest/csv_to_queue.py"]
    restart: on-failure


  anomaly-detector:
    image: alpine
    command: ["sh", "-c", "while true; do sleep 60; done"]
    restart: always


  api:
    build: .
    container_name: ais-api
    command: ["python", "-m", "uvicorn", "api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=ais
      - DB_USER=appuser
      - DB_PASS=password
    depends_on:
      - rabbitmq


  frontend:
    build: .
    container_name: ais-frontend
    command: ["python", "-m", "streamlit", "run", "frontend/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    depends_on:
      - api


volumes:
  rabbitmq_data:
